export const get = {
  BID_CONFIG_BY_STYLE_ID: 'BID_CONFIG_BY_STYLE_ID',
  CURRENT_BID_CONFIG_BY_STYLE_ID: 'CURRENT_BID_CONFIG_BY_STYLE_ID',
  UPDATED_BID_CONFIG_BY_STYLE_ID: 'UPDATED_BID_CONFIG_BY_STYLE_ID'
}

export const mutator = {
  SET_CURRENT_BID_CONFIGS: 'SET_CURRENT_BID_CONFIGS',
  SET_UPDATED_BID_CONFIGS: 'SET_UPDATED_BID_CONFIGS',
  SET_BID_CONFIG_OPTIONS: 'SET_BID_CONFIG_OPTIONS',
  SET_BID_CONFIG_ERRORS: 'SET_BID_CONFIG_ERRORS',
  CLEAR_BID_CONFIG_ERRORS: 'CLEAR_BID_CONFIG_ERRORS',
  SET_BID_CONFIG_VALIDITY: 'SET_BID_CONFIG_VALIDITY'
}

export const actor = {
  GET_BID_CONFIGS: 'GET_CONFIGS',
  POST_BID_CONFIGS: 'POST_CONFIGS',
  GET_BID_OPTIONS: 'GET_BID_OPTIONS',
  UPDATE_BID_CONFIG_BY_STYLE_ID: 'UPDATE_BID_CONFIG_BY_STYLE_ID',
  UPDATE_BID_CONFIG_BY_STYLES: 'UPDATE_BID_CONFIG_BY_STYLES',
  VALIDATE_BID_CONFIG: 'VALIDATE_BID_CONFIG',
  CLEAR_NULL_BID_CONFIGS: 'CLEAR_NULL_BID_CONFIGS',
  HANDLE_ERROR: 'HANDLE_ERROR'
}
